function Hd = hp_fir2
%HP_FIR2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and DSP System Toolbox 9.14.
% Generated on: 16-Mar-2022 01:42:43

% FIR Window Highpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 15000;  % Sampling Frequency

Fstop = 380;             % Stopband Frequency
Fpass = 1200;            % Passband Frequency
Dstop = 0.001;           % Stopband Attenuation
Dpass = 0.057501127785;  % Passband Ripple
flag  = 'scale';         % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fstop Fpass]/(Fs/2), [0 1], [Dpass Dstop]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
%Hd = dfilt.dffir(b);

%Quantize
lsb = 2^-9;
int_part = b./lsb;
int_part = round(int_part);
b_q = int_part.*lsb;

Hd = dfilt.dffir(b_q);
%Hd_q = dfilt.dffir(b_q);

%freqz(Hd)

% [EOF]
