function Hd = hp_fir1
%HP_FIR1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 04-Mar-2022 09:56:08

% FIR Window Highpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 15000;  % Sampling Frequency

Fstop = 380;             % Stopband Frequency
Fpass = 1200;            % Passband Frequency
Dstop = 0.001;           % Stopband Attenuation
Dpass = 0.057501127785;  % Passband Ripple
flag  = 'noscale';       % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fstop Fpass]/(Fs/2), [0 1], [Dpass Dstop]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
Hd = dfilt.dffir(b);

%Quantize
%lsb = 2^-7;
%int_part = b./lsb;
%int_part = round(int_part);
%b_q = int_part.*lsb;

%Hd = dfilt.dffir(b);
%Hd_q = dfilt.dffir(b_q);
freqz(Hd)
%freqz(Hd_q)



% [EOF]
